Disable GRADLE_METADATA feature if it will cause build to fail
> Task :runJsTests FAILED
/home/eric/PabstSoftware/git/yested_fw/node_modules/bootstrap/dist/js/bootstrap.js:121
    $.fn.emulateTransitionEnd = transitionEndEmulator;
                              ^

TypeError: Cannot set property 'emulateTransitionEnd' of undefined
    at setTransitionEndSupport (/home/eric/PabstSoftware/git/yested_fw/node_modules/bootstrap/dist/js/bootstrap.js:121:31)